kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dpowersnews/aspreactapp.api
