kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: backend-docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.api
    when:
      branch:
        - master
  - name: client-app-docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.client-app
      dockerfile: ./client-app/Dockerfile
      context: ./client-app
      when:
        branch:
          - master
