kind: pipeline
type: docker
name: AspReactAppBuild

platform:
  os: linux
  arch: amd64
# arch: arm

trigger:
  branch:
  - master

steps:
  - name: backend-docker
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.api.amd
  - name: client-app-docker
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.client-app.amd
      dockerfile: ./client-app/Dockerfile
      context: ./client-app


