kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

trigger:
  branch:
  - master

steps:
  - name: backend-docker
    image: plugins/docker
    group: build
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.api
  - name: client-app-docker
    image: plugins/docker
    group: build
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.client-app
      dockerfile: ./client-app/Dockerfile
      context: ./client-app


