#BACKEND BUILD
kind: pipeline
type: docker
name: backend-build

platform:
  os: linux
  arch: arm

trigger:
  branch:
  - master

steps:
  - name: backend-docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.api

#CLIENT-APP BUILD
kind: pipeline
type: docker
name: client-app-build

platform:
  os: linux
  arch: arm

trigger:
  branch:
  - master

steps:
  - name: client-app-docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dpowersnewg/aspreactapp.client-app
      dockerfile: ./client-app/Dockerfile
      context: ./client-app