version: "3.4"

services:
  mongodb:
    image: 'mongo:latest'
  client:
    build:
      context: ./client-app
    ports:
      - '5001:80'
  backend:
    build:
      context: .
    ports:
      - '5050:5050'